using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace SwapKino.Api.Migrations;
[DbContext(typeof(SwapKinoDbContext))]
[Migration("202608060001_Initial")]
public partial class Initial : Migration
{
 protected override void Up(MigrationBuilder m){
  m.CreateTable("AspNetRoles",t=>new{Id=t.Column<Guid>(),Name=t.Column<string>(maxLength:256,nullable:true),NormalizedName=t.Column<string>(maxLength:256,nullable:true),ConcurrencyStamp=t.Column<string>(nullable:true)},constraints:c=>c.PrimaryKey("PK_AspNetRoles",x=>x.Id));
  m.CreateTable("Movies",t=>new{TmdbId=t.Column<int>(),Title=t.Column<string>(maxLength:500),OriginalTitle=t.Column<string>(maxLength:500,nullable:true),Overview=t.Column<string>(nullable:true),ReleaseDate=t.Column<string>(maxLength:20,nullable:true),RuntimeMinutes=t.Column<int>(nullable:true),VoteAverage=t.Column<double>(),VoteCount=t.Column<int>(),Popularity=t.Column<double>(),PosterPath=t.Column<string>(maxLength:500,nullable:true),BackdropPath=t.Column<string>(maxLength:500,nullable:true),DetailsState=t.Column<string>(maxLength:30),Payload=t.Column<string>(),UpdatedAt=t.Column<DateTime>()},constraints:c=>c.PrimaryKey("PK_Movies",x=>x.TmdbId));
  m.CreateTable("AspNetUsers",t=>new{Id=t.Column<Guid>(),UserName=t.Column<string>(maxLength:256,nullable:true),NormalizedUserName=t.Column<string>(maxLength:256,nullable:true),Email=t.Column<string>(maxLength:256,nullable:true),NormalizedEmail=t.Column<string>(maxLength:256,nullable:true),EmailConfirmed=t.Column<bool>(),PasswordHash=t.Column<string>(nullable:true),SecurityStamp=t.Column<string>(nullable:true),ConcurrencyStamp=t.Column<string>(nullable:true),PhoneNumber=t.Column<string>(nullable:true),PhoneNumberConfirmed=t.Column<bool>(),TwoFactorEnabled=t.Column<bool>(),LockoutEnd=t.Column<DateTimeOffset>(nullable:true),LockoutEnabled=t.Column<bool>(),AccessFailedCount=t.Column<int>(),DisplayName=t.Column<string>(maxLength:256,nullable:true),KinopoiskProfileUrl=t.Column<string>(maxLength:500,nullable:true),CreatedAt=t.Column<DateTime>()},constraints:c=>c.PrimaryKey("PK_AspNetUsers",x=>x.Id));
  m.CreateTable("ImportJobs",t=>new{Id=t.Column<Guid>(),UserId=t.Column<Guid>(),ProfileUrl=t.Column<string>(maxLength:500),Status=t.Column<string>(maxLength:40),Progress=t.Column<int>(),ImportedCount=t.Column<int>(),Error=t.Column<string>(nullable:true),Checkpoint=t.Column<string>(),CreatedAt=t.Column<DateTime>(),UpdatedAt=t.Column<DateTime>()},constraints:c=>{c.PrimaryKey("PK_ImportJobs",x=>x.Id);c.ForeignKey("FK_ImportJobs_AspNetUsers_UserId",x=>x.UserId,"AspNetUsers","Id",onDelete:ReferentialAction.Cascade);});
  m.CreateTable("UserActions",t=>new{Id=t.Column<Guid>(),UserId=t.Column<Guid>(),TmdbId=t.Column<int>(),ActionType=t.Column<string>(maxLength:40),Value=t.Column<double>(nullable:true),IdempotencyKey=t.Column<string>(maxLength:100),CreatedAt=t.Column<DateTime>()},constraints:c=>{c.PrimaryKey("PK_UserActions",x=>x.Id);c.ForeignKey("FK_UserActions_AspNetUsers_UserId",x=>x.UserId,"AspNetUsers","Id",onDelete:ReferentialAction.Cascade);c.ForeignKey("FK_UserActions_Movies_TmdbId",x=>x.TmdbId,"Movies","TmdbId",onDelete:ReferentialAction.Cascade);});
  m.CreateTable("OutboxEvents",t=>new{Id=t.Column<Guid>(),Topic=t.Column<string>(maxLength:120),Payload=t.Column<string>(),Published=t.Column<bool>(),CreatedAt=t.Column<DateTime>()},constraints:c=>c.PrimaryKey("PK_OutboxEvents",x=>x.Id));
  m.CreateIndex("IX_AspNetUsers_NormalizedEmail","AspNetUsers","NormalizedEmail",unique:true);m.CreateIndex("IX_AspNetUsers_NormalizedUserName","AspNetUsers","NormalizedUserName",unique:true);m.CreateIndex("IX_UserActions_UserId_IdempotencyKey","UserActions",new[]{"UserId","IdempotencyKey"},unique:true);m.CreateIndex("IX_UserActions_UserId_TmdbId","UserActions",new[]{"UserId","TmdbId"});m.CreateIndex("IX_ImportJobs_UserId_CreatedAt","ImportJobs",new[]{"UserId","CreatedAt"});m.CreateIndex("IX_OutboxEvents_Published","OutboxEvents","Published");
 }
 protected override void Down(MigrationBuilder m){m.DropTable("OutboxEvents");m.DropTable("UserActions");m.DropTable("ImportJobs");m.DropTable("AspNetUsers");m.DropTable("Movies");m.DropTable("AspNetRoles");}
}
