"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Check, Circle, Clock, Loader2, RotateCcw, X } from "lucide-react";
import { api, type ImportStatus } from "@/lib/api";
import { useAppStore } from "@/lib/store";
import { cn } from "@/lib/utils";

const STEPS = [
  { key: "Queued", title: "Ожидание" },
  { key: "Scraping", title: "Получение страниц" },
  { key: "Matching", title: "Сопоставление TMDB" },
  { key: "Applying", title: "Применение" },
];
const TERMINAL = new Set(["Completed", "CompletedWithWarnings", "Failed", "Cancelled"]);

export function ImportStart() {
  const router = useRouter(); const [url, setUrl] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const start = async () => { setLoading(true); setError(null); try { const job = await api.importProfile(url.trim()); router.push(`/imports/kinopoisk/${job.id}`); } catch (cause) { const apiError = cause as Error & { data?: { id?: string } }; if (apiError.data?.id) router.push(`/imports/kinopoisk/${apiError.data.id}`); else setError(apiError.message); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-2xl px-4 py-12"><h1 className="text-3xl font-bold">Импорт из Кинопоиска</h1><p className="mt-2 text-muted-foreground">Перенесём оценки и просмотренные фильмы. Повторный импорт обновит изменившиеся оценки и не создаст дубли.</p><div className="glass-panel mt-8 rounded-2xl p-6"><label className="text-sm font-medium">Ссылка на публичный профиль</label><input type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://www.kinopoisk.ru/user/123456/" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:ring-2 focus:ring-rating/40"/><p className="mt-3 text-xs text-muted-foreground">На следующем экране появится живой прогресс. Во время получения страниц лучше не закрывать вкладку.</p>{error && <p className="mt-3 text-sm text-skip">{error}</p>}<button disabled={!url.trim() || loading} onClick={() => void start()} className="mt-5 rounded-full bg-white px-5 py-2.5 text-sm font-bold text-black disabled:opacity-40">{loading ? "Запускаем…" : "Начать импорт"}</button></div></div>;
}

export function ImportProgress({ jobId }: { jobId: string }) {
  const [status, setStatus] = useState<ImportStatus | null>(null); const [error, setError] = useState<string | null>(null); const [pollRun, setPollRun] = useState(0); const refreshLibrary = useAppStore((state) => state.refreshLibrary);
  useEffect(() => { let active = true; let timer: number | undefined; let synced = false; const poll = async () => { try { const next = await api.importStatus(jobId); if (!active) return; setStatus(next); setError(null); if (TERMINAL.has(next.status)) { if ((next.status === "Completed" || next.status === "CompletedWithWarnings") && !synced) { synced = true; await refreshLibrary().catch(() => undefined); } return; } timer = window.setTimeout(poll, next.status === "WaitingForUser" ? 3000 : 1500); } catch (cause) { if (!active) return; setError(cause instanceof Error ? cause.message : "Не удалось получить состояние"); timer = window.setTimeout(poll, 4000); } }; void poll(); return () => { active = false; if (timer) window.clearTimeout(timer); }; }, [jobId, refreshLibrary, pollRun]);
  const phase = status?.phase ?? status?.status ?? "Queued"; const activeStep = Math.max(0, STEPS.findIndex((step) => step.key === phase)); const progress = status?.overallProgress ?? status?.progress ?? 0; const etaSeconds = status?.etaSeconds ?? status?.estimatedRemainingSeconds; const eta = useMemo(() => formatEta(etaSeconds), [etaSeconds]);
  return <div className="mx-auto max-w-3xl px-4 py-10"><h1 className="text-3xl font-bold">Импорт из Кинопоиска</h1><p className="mt-2 text-sm text-muted-foreground">Операция {jobId}</p><div className="glass-panel mt-7 rounded-2xl p-5 sm:p-7"><div className="grid grid-cols-4 gap-2">{STEPS.map((step, index) => { const done = index < activeStep || status?.status === "Completed" || status?.status === "CompletedWithWarnings"; const activeNow = index === activeStep && !TERMINAL.has(status?.status ?? ""); return <div key={step.key} className="relative text-center"><div className={cn("mx-auto h-9 w-9 rounded-full border grid place-items-center", done && "bg-like border-like text-black", activeNow && "border-rating text-rating")}>{done ? <Check className="h-4 w-4"/> : activeNow ? <Loader2 className="h-4 w-4 animate-spin"/> : <Circle className="h-3 w-3"/>}</div><p className="mt-2 text-[11px] sm:text-xs">{step.title}</p></div>; })}</div><div className="mt-8 h-2 overflow-hidden rounded-full bg-white/8"><div className="h-full bg-rating transition-all duration-500" style={{ width: `${Math.max(0, Math.min(100, progress))}%` }}/></div><div className="mt-3 flex justify-between text-sm"><b>{Math.round(progress)}%</b>{eta && <span className="text-muted-foreground flex gap-1"><Clock className="h-4 w-4"/>{eta}</span>}</div><Stats status={status}/>
      {!TERMINAL.has(status?.status ?? "") && <p className="mt-5 rounded-xl bg-white/5 p-3 text-xs text-muted-foreground">Пожалуйста, не закрывай эту страницу: получение данных Кинопоиска может занять несколько минут.</p>}
      {status?.status === "WaitingForUser" && <Captcha jobId={jobId} status={status} onChange={setStatus}/>} {status?.status === "Completed" && <Result ok title="Импорт завершён" text="Библиотека и персональные киноплёнки уже обновлены."/>}{status?.status === "CompletedWithWarnings" && <Result ok title="Импорт завершён с предупреждениями" text="Всё, что удалось надёжно сопоставить, добавлено. Несопоставленные позиции показаны в статистике."/>}{status?.status === "Failed" && <FailedResult jobId={jobId} status={status} onChange={setStatus} onResumed={() => setPollRun((value) => value + 1)}/>} {status?.status === "Cancelled" && <Result title="Импорт отменён"/>}{error && <p className="mt-4 text-sm text-skip">{error}</p>}
    </div></div>;
}
function Stats({ status }: { status: ImportStatus | null }) { const rows = [["Страниц", `${status?.pagesProcessed ?? 0}${status?.pagesTotal ? ` / ${status.pagesTotal}` : ""}`], ["Найдено", status?.discoveredCount ?? 0], ["Сопоставлено", status?.matchedCount ?? 0], ["Применено", status?.appliedCount ?? status?.importedCount ?? 0], ["Не найдено", status?.unmatchedCount ?? 0]]; return <div className="mt-6 grid grid-cols-2 sm:grid-cols-5 gap-2">{rows.map(([label,value]) => <div key={label} className="rounded-xl bg-black/20 p-3"><p className="text-lg font-bold">{value}</p><p className="text-[11px] text-muted-foreground">{label}</p></div>)}</div>; }
function Captcha({ jobId, status, onChange }: { jobId: string; status: ImportStatus; onChange: (next: ImportStatus) => void }) { const [busy, setBusy] = useState(false); return <div className="mt-5 rounded-xl border border-rating/30 bg-rating/5 p-4"><h2 className="font-semibold">Кинопоиск просит подтверждение</h2><p className="mt-1 text-xs text-muted-foreground">Открой проверку, пройди CAPTCHA и вернись сюда.</p>{status.captcha?.screenshotBase64 && <img className="mt-3 max-h-52 w-full rounded-lg object-contain" alt="CAPTCHA" src={`data:${status.captcha.screenshotMimeType ?? "image/png"};base64,${status.captcha.screenshotBase64}`}/>}<div className="mt-3 flex flex-wrap gap-2">{status.captcha?.novncUrl && <a href={status.captcha.novncUrl} target="_blank" rel="noreferrer" className="rounded-full bg-rating px-4 py-2 text-xs font-bold text-black">Открыть проверку</a>}<button disabled={busy} onClick={async () => { setBusy(true); try { onChange(await api.importResume(jobId)); } finally { setBusy(false); } }} className="rounded-full bg-white px-4 py-2 text-xs font-bold text-black"><RotateCcw className="inline h-3 w-3"/> Продолжить</button><button onClick={async () => onChange(await api.importCancel(jobId))} className="rounded-full border px-4 py-2 text-xs"><X className="inline h-3 w-3"/> Отменить</button></div></div>; }
function FailedResult({ jobId, status, onChange, onResumed }: { jobId: string; status: ImportStatus; onChange: (next: ImportStatus) => void; onResumed: () => void }) { const [busy, setBusy] = useState(false); const [retryError, setRetryError] = useState<string | null>(null); return <div className="mt-6 rounded-xl border border-skip/30 bg-skip/10 p-4"><h2 className="font-semibold">Импорт остановлен</h2><p className="mt-1 text-sm text-muted-foreground">{status.error ?? "Кинопоиск вернул неожиданные данные."}</p><button disabled={busy} onClick={async () => { setBusy(true); setRetryError(null); try { onChange(await api.importResume(jobId)); onResumed(); } catch (cause) { setRetryError(cause instanceof Error ? cause.message : "Не удалось продолжить импорт"); } finally { setBusy(false); } }} className="mt-3 rounded-full bg-white px-4 py-2 text-xs font-bold text-black disabled:opacity-50"><RotateCcw className={cn("inline h-3 w-3", busy && "animate-spin")}/> {busy ? "Продолжаем…" : "Продолжить"}</button>{retryError && <p className="mt-2 text-xs text-skip">{retryError}</p>}</div>; }
function Result({ ok, title, text }: { ok?: boolean; title: string; text?: string }) { return <div className={cn("mt-6 rounded-xl border p-4", ok ? "border-like/30 bg-like/10" : "border-skip/30 bg-skip/10")}><h2 className="font-semibold">{title}</h2>{text && <p className="mt-1 text-sm text-muted-foreground">{text}</p>}</div>; }
function formatEta(seconds?: number | null) { if (!seconds || seconds <= 0) return null; if (seconds < 60) return `около ${Math.ceil(seconds)} с`; return `около ${Math.ceil(seconds / 60)} мин`; }
