using System.Text.Json;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using StackExchange.Redis;
using SwapKino.Api;

var builder=Host.CreateApplicationBuilder(args); builder.Services.AddDbContext<SwapKinoDbContext>(o=>o.UseNpgsql(builder.Configuration.GetConnectionString("Default")??builder.Configuration["DATABASE_URL"])); builder.Services.AddSingleton<IConnectionMultiplexer>(_=>ConnectionMultiplexer.Connect(builder.Configuration["REDIS_URL"]??"redis-runtime:6379,abortConnect=false")); builder.Services.AddHttpClient("selenium",c=>c.BaseAddress=new Uri(builder.Configuration["SELENIUM_URL"]??"http://selenium-service:8081")); builder.Services.AddHostedService<OutboxWorker>(); var host=builder.Build(); await host.RunAsync();
public sealed class OutboxWorker(IServiceScopeFactory scopes,IConnectionMultiplexer redis,IHttpClientFactory http,ILogger<OutboxWorker> log):BackgroundService
{
 protected override async Task ExecuteAsync(CancellationToken stoppingToken){while(!stoppingToken.IsCancellationRequested){try{using var scope=scopes.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SwapKinoDbContext>();var events=await db.OutboxEvents.Where(x=>!x.Published).OrderBy(x=>x.CreatedAt).Take(50).ToListAsync(stoppingToken);foreach(var e in events){await redis.GetDatabase().StreamAddAsync("swapkino:events",new[]{new NameValueEntry("topic",e.Topic),new NameValueEntry("payload",e.Payload)});e.Published=true;if(e.Topic=="kinopoisk.import"){var data=JsonSerializer.Deserialize<ImportPayload>(e.Payload)!;var job=await db.ImportJobs.FindAsync([data.JobId],stoppingToken);if(job is not null){job.Status="Running";job.Progress=5;await db.SaveChangesAsync(stoppingToken);await RunImport(job,data.ProfileUrl,stoppingToken);}}}await db.SaveChangesAsync(stoppingToken);}catch(Exception ex){log.LogError(ex,"Outbox processing failed");}await Task.Delay(TimeSpan.FromSeconds(2),stoppingToken);}}
 private async Task RunImport(ImportJob job,string profileUrl,CancellationToken ct){try{var response=await http.CreateClient("selenium").PostAsJsonAsync("/api/v1/kinopoisk/ratings",new{profile_url=profileUrl,include_unrated=true},ct);if((int)response.StatusCode==409){job.Status="WaitingForUser";job.Progress=25;job.Checkpoint=await response.Content.ReadAsStringAsync(ct);}else if(response.IsSuccessStatusCode){using var doc=JsonDocument.Parse(await response.Content.ReadAsStringAsync(ct));job.Status="Completed";job.Progress=100;job.ImportedCount=doc.RootElement.TryGetProperty("total",out var total)?total.GetInt32():0;}else{job.Status="Failed";job.Error=$"Selenium returned {(int)response.StatusCode}";}}catch(Exception ex){job.Status="Failed";job.Error=ex.Message;}}
 private sealed record ImportPayload(Guid JobId,Guid UserId,string ProfileUrl);
}
