"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Check, ChevronRight, Copy, Heart, MessageCircle, Settings, Shield, Star, UserPlus, Users } from "lucide-react";
import { api, mapApiMovie, type ApiLibraryItem, type PublicProfile, type PublicProfileComment, type PublicUser } from "@/lib/api";
import { useAppStore } from "@/lib/store";
import { trackEvent } from "@/components/common/PlausibleAnalytics";

function ratingClass(value: number) { return value >= 8 ? "bg-emerald-400 text-black" : value >= 5 ? "bg-amber-300 text-black" : "bg-rose-400 text-black"; }

export function PublicProfileView({ id }: { id: string }) {
  const currentUser = useAppStore((state) => state.user);
  const [profile, setProfile] = useState<PublicProfile | null>(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setProfile(await api.publicProfile(id)); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Профиль недоступен"); } }, [id]);
  // The effect synchronizes the route id with the remote profile resource.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  if (error) return <div className="mx-auto max-w-3xl px-4 py-20 text-center"><p>{error}</p><Link href="/" className="mt-4 inline-block text-rating">На главную</Link></div>;
  if (!profile) return <div className="py-24 text-center text-muted-foreground">Загружаем профиль…</div>;
  const isSelf = currentUser?.id === id;
  const share = async () => { await navigator.clipboard.writeText(`${window.location.origin}/profile/${id}`); trackEvent("profile_share"); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  const toggleFollow = async () => { if (!currentUser) return; const follows = profile.relation === "following" || profile.relation === "friends"; const response = follows ? await api.unfollow(id) : await api.follow(id); setProfile({ ...profile, relation: response.relation, statistics: { ...profile.statistics, followersCount: profile.statistics.followersCount + (follows ? -1 : 1) } }); };
  return <main className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 py-6 space-y-7">
    <Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Назад</Link>
    <section className="glass-panel rounded-3xl p-6 sm:p-8 relative overflow-hidden"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-rating/10 blur-3xl" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center"><Avatar user={profile.user} large /><div className="min-w-0 flex-1"><h1 className="truncate text-2xl font-bold">{profile.user.name}</h1><p className="text-sm text-muted-foreground">{profile.statistics.ratingsCount} оценок · {profile.statistics.watchedCount} просмотров · средняя {profile.statistics.averageRating || "—"}</p><p className="mt-1 text-xs text-muted-foreground">{profile.statistics.followersCount} подписчиков · {profile.statistics.followingCount} подписок</p>{!isSelf && profile.relation !== "none" && <p className="mt-1 text-xs text-rating">{profile.relation === "friends" ? "Вы друзья" : profile.relation === "following" ? "Вы подписаны" : "Подписан на вас"}</p>}</div><div className="flex flex-wrap gap-2">{isSelf && <><Link href="/profile/settings" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-4 py-2.5 text-sm font-semibold hover:border-rating/50"><Settings className="h-4 w-4 text-rating" /> Настройки</Link>{currentUser.roles.includes("admin") && <Link href="/admin" className="inline-flex items-center gap-2 rounded-xl bg-rating px-4 py-2.5 text-sm font-bold text-black"><Shield className="h-4 w-4" /> Админка</Link>}</>}{!isSelf && currentUser && <button type="button" onClick={() => void toggleFollow()} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-black">{profile.relation === "following" || profile.relation === "friends" ? "Отписаться" : <><UserPlus className="h-4 w-4" /> Подписаться</>}</button>}<button type="button" onClick={() => void share()} aria-label={copied ? "Ссылка скопирована" : "Поделиться профилем"} title={copied ? "Ссылка скопирована" : "Поделиться профилем"} className="inline-flex h-11 w-11 items-center justify-center rounded-xl border border-white/10 bg-black/20 hover:border-rating/50">{copied ? <Check className="h-4 w-4 text-rating" /> : <Copy className="h-4 w-4 text-rating" />}</button></div></div></section>
    <div className="grid gap-4 md:grid-cols-2"><ProfileBlock title="Подписчики" icon={<Users className="h-5 w-5 text-rating" />} action={`/profile/${id}/followers`}><People items={profile.followers} /></ProfileBlock><ProfileBlock title="Подписки" icon={<Users className="h-5 w-5 text-rating" />} action={`/profile/${id}/following`}><People items={profile.following} /></ProfileBlock><ProfileBlock title="Избранное" icon={<Heart className="h-5 w-5 text-like" fill="currentColor" />} action={`/profile/${id}/favorites`}><MovieStrip items={profile.favorites} /></ProfileBlock><ProfileBlock title="Оценки" icon={<Star className="h-5 w-5 text-rating" fill="currentColor" />} action={`/profile/${id}/ratings`}><MovieStrip items={profile.ratings} showRating /></ProfileBlock></div>
    <TopComments comments={profile.comments} />
  </main>;
}

function Avatar({ user, large = false }: { user: PublicUser; large?: boolean }) { return <div className={`${large ? "h-20 w-20 text-3xl" : "h-9 w-9 text-xs"} shrink-0 overflow-hidden rounded-full bg-gradient-to-br from-rating/80 to-skip/60 grid place-items-center font-bold text-black`}>{user.avatarUrl ? <img src={user.avatarUrl} alt="" className="h-full w-full object-cover" /> : user.name[0]?.toUpperCase()}</div>; }
function ProfileBlock({ title, icon, action, children }: { title: string; icon: ReactNode; action: string; children: ReactNode }) {
  const router = useRouter();
  const open = () => router.push(action);
  return <section role="link" tabIndex={0} aria-label={`Открыть раздел «${title}»`} onClick={(event) => { if ((event.target as HTMLElement).closest("a,button")) return; open(); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); open(); } }} className="glass-panel cursor-pointer rounded-2xl p-5 transition hover:border-rating/40 focus:outline-none focus:ring-2 focus:ring-rating/60"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-bold">{icon}{title}</h2><Link href={action} aria-label={`Открыть раздел «${title}»`} title="Смотреть все" className="text-muted-foreground hover:text-foreground"><ChevronRight className="h-4 w-4" /></Link></div>{children}</section>;
}
function MovieStrip({ items, showRating = false }: { items: ApiLibraryItem[]; showRating?: boolean }) { if (!items.length) return <p className="text-sm text-muted-foreground">Пока пусто.</p>; return <div className="grid grid-cols-4 gap-2 sm:grid-cols-5">{items.slice(0, 10).map((item) => { const movie = item.movie ? mapApiMovie(item.movie) : null; return movie ? <Link key={`${item.tmdbId}:${item.isSeries}`} href={`/movie/${item.tmdbId}${item.isSeries ? "?series=1" : ""}`} className="group min-w-0"><div className="relative aspect-[2/3] overflow-hidden rounded-lg border border-white/10 bg-white/5">{movie.posterUrl && <img src={movie.posterUrl} alt={movie.title} className="h-full w-full object-cover transition group-hover:scale-105" />}{showRating && item.rating != null && <span className={`absolute bottom-1 right-1 rounded-md px-1.5 py-0.5 text-xs font-black ${ratingClass(item.rating)}`}>{item.rating}</span>}</div><p className="mt-1 truncate text-[11px] text-muted-foreground">{movie.title}</p></Link> : null; })}</div>; }
function People({ items }: { items: PublicUser[] }) { if (!items.length) return <p className="text-sm text-muted-foreground">Пока пусто.</p>; return <div className="flex flex-wrap gap-2">{items.map((person) => <Link key={person.id} href={`/profile/${person.id}`} className="inline-flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-sm hover:border-rating/50"><Avatar user={person} /><span className="max-w-32 truncate">{person.name}</span></Link>)}</div>; }
function TopComments({ comments }: { comments: PublicProfileComment[] }) { return <section><h2 className="mb-3 flex items-center gap-2 text-xl font-bold"><MessageCircle className="h-5 w-5 text-rating" />Топ комментариев</h2>{comments.length ? <div className="space-y-3">{comments.map((comment) => { const movie = comment.movie ? mapApiMovie(comment.movie) : null; const query = comment.isSeries ? `?series=1&comment=${comment.id}` : `?comment=${comment.id}`; return <article key={comment.id} className="glass-panel flex gap-3 rounded-2xl p-4"><Link href={`/movie/${comment.tmdbId}${query}`} className="h-16 w-11 shrink-0 overflow-hidden rounded bg-white/5">{movie?.posterUrl && <img src={movie.posterUrl} alt={movie.title} className="h-full w-full object-cover" />}</Link><div className="min-w-0 flex-1"><Link href={`/movie/${comment.tmdbId}${query}`} className="text-sm font-bold hover:text-rating">{movie?.title ?? `Фильм #${comment.tmdbId}`}</Link><p className="mt-1 text-sm text-muted-foreground">{comment.text}</p><p className="mt-2 text-xs text-muted-foreground">{comment.likes} лайков · {comment.score} score</p></div></article>; })}</div> : <p className="text-sm text-muted-foreground">Комментариев пока нет.</p>}</section>; }
