"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { MessageCircle, ThumbsDown, ThumbsUp, Trash2 } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { api, type MovieComment } from "@/lib/api";
import { useAppStore } from "@/lib/store";
import { trackEvent } from "@/components/common/PlausibleAnalytics";

function CommentRow({ comment, onReply, onRefresh }: { comment: MovieComment; onReply: (id: string) => void; onRefresh: () => void }) {
  const user = useAppStore((state) => state.user); const [busy, setBusy] = useState(false);
  const react = async (type: "like" | "dislike") => { if (!user) return; setBusy(true); try { if (comment.myReaction === type) await api.removeCommentReaction(comment.id); else await api.reactComment(comment.id, type); onRefresh(); } finally { setBusy(false); } };
  const remove = async () => { if (!user || (!comment.isMine && !user.roles.includes("admin"))) return; setBusy(true); try { await api.deleteComment(comment.id); onRefresh(); } finally { setBusy(false); } };
  return <article id={`comment-${comment.id}`} className={`rounded-2xl border p-4 transition ${comment.isMine ? "border-rating/50 bg-rating/5" : "border-white/10 bg-white/[.03]"}`}><div className="flex gap-3"><Link href={`/profile/${comment.author.id}`} className="h-9 w-9 shrink-0 rounded-full overflow-hidden bg-rating/20 grid place-items-center text-xs font-bold">{comment.author.avatarUrl ? <img src={comment.author.avatarUrl} alt="" className="h-full w-full object-cover" /> : comment.author.name[0]?.toUpperCase()}</Link><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-xs"><Link href={`/profile/${comment.author.id}`} className="font-bold hover:text-rating">{comment.author.name}</Link>{comment.isMine && <span className="text-rating">вы</span>}<time className="text-muted-foreground">{new Date(comment.createdAt).toLocaleDateString("ru-RU")}</time></div><p className="mt-2 whitespace-pre-wrap text-sm">{comment.deletedAt ? <span className="italic text-muted-foreground">Комментарий удалён</span> : comment.text}</p><div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><button type="button" disabled={!user || busy} onClick={() => void react("like")} className={comment.myReaction === "like" ? "text-emerald-300" : "hover:text-emerald-300"}><ThumbsUp className="inline h-3.5 w-3.5" /> {comment.likes}</button><button type="button" disabled={!user || busy} onClick={() => void react("dislike")} className={comment.myReaction === "dislike" ? "text-rose-300" : "hover:text-rose-300"}><ThumbsDown className="inline h-3.5 w-3.5" /> {comment.dislikes}</button>{user && !comment.deletedAt && <button type="button" onClick={() => onReply(comment.id)} className="hover:text-foreground"><MessageCircle className="inline h-3.5 w-3.5" /> Ответить</button>}{user && (comment.isMine || user.roles.includes("admin")) && !comment.deletedAt && <button type="button" disabled={busy} onClick={() => void remove()} className="hover:text-rose-300"><Trash2 className="inline h-3.5 w-3.5" /> Удалить</button>}</div></div></div>{comment.replies?.length ? <div className="mt-3 ml-4 space-y-3 border-l border-white/10 pl-3">{comment.replies.map((reply) => <CommentRow key={reply.id} comment={reply} onReply={onReply} onRefresh={onRefresh} />)}</div> : null}</article>;
}

export function MovieComments({ movieId, isSeries = false }: { movieId: number; isSeries?: boolean }) {
  const user = useAppStore((state) => state.user); const searchParams = useSearchParams(); const focusId = searchParams.get("comment");
  const [comments, setComments] = useState<MovieComment[]>([]); const [text, setText] = useState(""); const [replyTo, setReplyTo] = useState<string | null>(null); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [hasNext, setHasNext] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async (nextPage = page, focusCommentId?: string | null) => { setLoading(true); try { const response = await api.comments(movieId, isSeries, nextPage, focusCommentId); setComments(response.items); setPage(response.page); setTotal(response.totalCount); setHasNext(response.hasNextPage); } finally { setLoading(false); } }, [movieId, isSeries, page]);
  useEffect(() => { void load(1, focusId); }, [movieId, isSeries, focusId]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!loading && focusId) window.setTimeout(() => document.getElementById(`comment-${focusId}`)?.scrollIntoView({ behavior: "smooth", block: "center" }), 100); }, [loading, focusId, comments]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!text.trim() || !user) return; await api.addComment(movieId, text, replyTo, isSeries); trackEvent("comment_created", { is_reply: Boolean(replyTo) }); setText(""); setReplyTo(null); await load(page); };
  return <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mb-10"><h2 className="text-xl font-bold mb-3 flex gap-2"><span className="w-1 rounded-full bg-rating" />Комментарии <span className="text-sm font-normal text-muted-foreground">{total}</span></h2>{user ? <form onSubmit={submit} className="mb-5 rounded-2xl border border-white/10 bg-white/[.03] p-4"><textarea value={text} onChange={(event) => setText(event.target.value)} maxLength={2000} rows={3} placeholder={replyTo ? "Напиши ответ…" : "Поделись мнением о фильме…"} className="w-full resize-y bg-transparent text-sm outline-none" />{replyTo && <button type="button" onClick={() => setReplyTo(null)} className="mr-3 text-xs text-muted-foreground hover:text-foreground">Отменить ответ</button>}<button type="submit" disabled={!text.trim()} className="mt-3 rounded-full bg-white px-4 py-2 text-xs font-bold text-black disabled:opacity-40">Опубликовать</button></form> : <p className="mb-5 text-sm text-muted-foreground">Войди, чтобы оставить комментарий.</p>}{loading ? <p className="text-sm text-muted-foreground">Загружаем комментарии…</p> : comments.length ? <div className="space-y-3">{comments.map((comment) => <CommentRow key={comment.id} comment={comment} onReply={setReplyTo} onRefresh={() => void load(page)} />)}</div> : <p className="rounded-2xl border border-dashed border-white/15 py-8 text-center text-sm text-muted-foreground">Комментариев пока нет.</p>}{(page > 1 || hasNext) && <div className="mt-5 flex justify-center gap-2"><button type="button" disabled={page === 1 || loading} onClick={() => void load(page - 1)} className="rounded-full border border-white/15 px-4 py-2 text-sm disabled:opacity-40">Назад</button><span className="px-3 py-2 text-sm text-muted-foreground">Страница {page}</span><button type="button" disabled={!hasNext || loading} onClick={() => void load(page + 1)} className="rounded-full border border-white/15 px-4 py-2 text-sm disabled:opacity-40">Дальше</button></div>}</section>;
}
