"use client";
import { ArrowLeft, Copyright } from "lucide-react";
import { motion } from "framer-motion";
import Link from "next/link";
import { useAppStore } from "@/lib/store";

export function CopyrightView() {
  const setView = useAppStore((s) => s.setView);
  return <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-8"><button onClick={() => setView({ name: "feed" })} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-6"><ArrowLeft className="h-3.5 w-3.5" />На главную</button><motion.article initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="glass-panel rounded-3xl p-6 sm:p-10"><header className="flex items-center gap-3 mb-8"><div className="h-12 w-12 rounded-xl bg-rating/15 text-rating flex items-center justify-center"><Copyright className="h-6 w-6" /></div><div><h1 className="text-2xl font-bold">Правообладателям / Copyright</h1><p className="text-sm text-muted-foreground">Порядок обращений по контенту</p></div></header><div className="space-y-5 text-sm leading-relaxed text-foreground/90"><p>СвайпКино не размещает собственные копии фильмов. Названия, описания, постеры и другие сведения о произведениях используются как метаданные и предоставляются внешними источниками; ссылки на просмотр ведут на сторонние площадки.</p><h2 className="font-bold text-base">Запрос на удаление или исправление</h2><p>Напишите на <a href="mailto:steammail_38@mail.ru" className="text-rating hover:underline">steammail_38@mail.ru</a> с темой «Copyright». Укажите название произведения, ссылку на страницу, описание права/нарушения и контакт для ответа. Мы рассмотрим обращение и при необходимости ограничим отображение спорного материала.</p><h2 className="font-bold text-base">Права на программное обеспечение и медиаматериалы</h2><p>Исходный код проекта распространяется по <Link href="/license" className="text-rating hover:underline">MIT License</Link>. Это не передаёт права на названия, изображения, логотипы, трейлеры и иные материалы третьих лиц. Их права сохраняются за соответствующими правообладателями.</p><p className="text-muted-foreground">Для запросов о персональных данных используйте тот же адрес с темой «Privacy».</p></div></motion.article></div>;
}
