"use client";

import { motion } from "framer-motion";
import { Shield, ArrowLeft, Database, Cookie, UserCheck } from "lucide-react";
import Link from "next/link";
import { useAppStore } from "@/lib/store";

export function PrivacyView() {
  const setView = useAppStore((s) => s.setView);

  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-8">
      <button type="button" onClick={() => setView({ name: "feed" })} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-6"><ArrowLeft className="h-3.5 w-3.5" /> На главную</button>
      <motion.article initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="glass-panel rounded-3xl p-6 sm:p-10">
        <header className="flex items-center gap-3 mb-8"><div className="h-12 w-12 rounded-xl bg-rating/15 text-rating flex items-center justify-center"><Shield className="h-6 w-6" /></div><div><h1 className="text-2xl font-bold">Политика конфиденциальности</h1><p className="text-sm text-muted-foreground">Версия 2026-09-11 · обновлено 11 сентября 2026</p></div></header>
        <div className="space-y-6 text-sm leading-relaxed text-foreground/90">
          <section><h2 className="font-bold text-base mb-2">1. Кто мы и что регулирует политика</h2><p>СвайпКино — открытый сервис для поиска фильмов и сериалов. Политика описывает обработку данных при регистрации, работе профиля, оценках, избранном, отметках о просмотре, подписках, комментариях, реакциях, уведомлениях и импорте публичного профиля Кинопоиска.</p></section>
          <section><h2 className="font-bold text-base mb-2 flex items-center gap-2"><Database className="h-4 w-4 text-rating" />2. Какие данные обрабатываются</h2><ul className="list-disc pl-5 space-y-1.5"><li><b>Аккаунт:</b> email, имя профиля, хеш пароля, дата создания и сведения о согласии.</li><li><b>Профиль и библиотека:</b> аватар, избранное, оценки, просмотренные фильмы, свайпы и даты действий.</li><li><b>Социальные функции:</b> подписки, взаимные статусы, публичные комментарии, ответы, лайки, дизлайки и уведомления.</li><li><b>Импорт:</b> ссылка на публичный профиль Кинопоиска, найденные записи, оценки, статусы сопоставления, прогресс и технические ошибки задания. Пароль Кинопоиска не запрашивается.</li><li><b>Сессии:</b> access JWT в localStorage и httpOnly refresh-cookie; в базе хранится только хеш refresh-токена.</li></ul><p className="mt-2 text-muted-foreground">Пароли не хранятся в открытом виде. В текущей Docker-конфигурации рекламные и видеоскрипты отключены; при их включении сторонние поставщики могут обрабатывать данные по собственным политикам.</p></section>
          <section><h2 className="font-bold text-base mb-2">3. Зачем это нужно</h2><p>Данные аккаунта нужны для входа и синхронизации между устройствами. Данные профиля и активности нужны для библиотеки, рекомендаций, публичного профиля и социальных функций. Комментарии и реакции нужны для показа обсуждений и расчёта их рейтинга. Уведомления нужны для сообщений о подписках, ответах и реакциях. Импорт нужен для сопоставления записей с TMDB и применения оценок в профиль.</p></section>
          <section><h2 className="font-bold text-base mb-2">4. Публичные данные</h2><p>Имя, аватар, оценки, просмотренные фильмы, избранное, счётчики связей и комментарии могут отображаться на публичной странице профиля. Email, хеш пароля, токены, технические ошибки и другие служебные данные в публичные ответы не включаются. Удалённый комментарий может сохраняться в дереве ответов как «Комментарий удалён».</p></section>
          <section><h2 className="font-bold text-base mb-2">5. Внешние сервисы</h2><p>Метаданные и изображения запрашиваются у TMDB; трейлеры могут встраиваться через YouTube; ссылка импорта обрабатывается сервисом импорта Кинопоиска; аватары хранятся в объектном хранилище проекта. При включении видеопровайдера или рекламы браузер может обращаться к соответствующему стороннему ресурсу. Эти поставщики применяют собственные политики конфиденциальности. Подробнее о контенте — на странице <Link href="/copyright" className="text-rating hover:underline">«Правообладателям / Copyright»</Link>.</p></section>
          <section><h2 className="font-bold text-base mb-2">6. Сроки хранения</h2><ul className="list-disc pl-5 space-y-1.5"><li>Данные активного аккаунта хранятся до удаления аккаунта или пока это необходимо для работы сервиса.</li><li>Сессии хранятся до истечения срока действия или отзыва.</li><li>При удалении аккаунта удаляются связанные профильные данные, подписки, комментарии, реакции и уведомления. Удалённые комментарии других пользователей могут оставаться в их тредах только как удалённые.</li><li>Технические журналы и резервные копии обрабатываются в рамках фактической инфраструктуры и её циклов обслуживания.</li></ul></section>
          <section><h2 className="font-bold text-base mb-2 flex items-center gap-2"><Cookie className="h-4 w-4 text-rating" />7. Cookies и localStorage</h2><p>Refresh-cookie необходима для продления сессии и не используется для слежения. Access-токен хранится локально для авторизации API. Гостевые оценки и избранное могут оставаться только в браузере до его очистки. Сторонние cookies и скрипты возможны только при включении соответствующих интеграций.</p></section>
          <section><h2 className="font-bold text-base mb-2 flex items-center gap-2"><UserCheck className="h-4 w-4 text-rating" />8. Права пользователя</h2><p>В настройках профиля можно изменить имя и аватар, сменить пароль и удалить аккаунт. По вопросам доступа, исправления или удаления данных напишите на <a href="mailto:steammail_38@mail.ru" className="text-rating hover:underline">steammail_38@mail.ru</a>. Удаление аккаунта также удаляет связанные социальные данные и публикации в пределах, описанных выше.</p></section>
          <section><h2 className="font-bold text-base mb-2">9. Изменения и контакты</h2><p>При существенном изменении политики мы обновим версию и дату на этой странице. По privacy- и copyright-запросам пишите на <a href="mailto:steammail_38@mail.ru" className="text-rating hover:underline">steammail_38@mail.ru</a>; технические вопросы можно задать в <a href="https://github.com/Vlan3ik/SwapKino/issues" target="_blank" rel="noopener noreferrer" className="text-rating hover:underline">GitHub Issues</a>.</p></section>
        </div>
      </motion.article>
    </div>
  );
}
