"use client";

import { motion } from "framer-motion";
import { Shield, ArrowLeft, Database, Cookie, UserCheck } from "lucide-react";
import Link from "next/link";
import { useAppStore } from "@/lib/store";

export function PrivacyView() {
  const setView = useAppStore((s) => s.setView);
  return <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-8">
    <button onClick={() => setView({ name: "feed" })} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-6"><ArrowLeft className="h-3.5 w-3.5" />На главную</button>
    <motion.article initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="glass-panel rounded-3xl p-6 sm:p-10">
      <header className="flex items-center gap-3 mb-8"><div className="h-12 w-12 rounded-xl bg-rating/15 text-rating flex items-center justify-center"><Shield className="h-6 w-6" /></div><div><h1 className="text-2xl font-bold">Политика конфиденциальности</h1><p className="text-sm text-muted-foreground">Версия 2026-08-10 · обновлено 10 августа 2026</p></div></header>
      <div className="space-y-6 text-sm leading-relaxed text-foreground/90">
        <section><h2 className="font-bold text-base mb-2">1. Кто мы и что регулирует политика</h2><p>СвайпКино — некоммерческий open-source сервис для подбора фильмов. Эта политика описывает обработку данных при регистрации, работе профиля, истории действий, свайпах и импорте публичного профиля Кинопоиска.</p></section>
        <section><h2 className="font-bold text-base mb-2 flex items-center gap-2"><Database className="h-4 w-4 text-rating" />2. Какие данные обрабатываются</h2><ul className="list-disc pl-5 space-y-1.5"><li><b>Аккаунт:</b> email, имя профиля, хеш пароля, дата создания и версия/дата согласия.</li><li><b>Профиль и история:</b> избранное, оценки, просмотренные/отмеченные фильмы, свайпы «нравится/пропустить», сигналы рекомендаций и даты действий.</li><li><b>Импорт Кинопоиска:</b> указанная ссылка на публичный профиль, идентификаторы и названия найденных записей, оценки, статусы сопоставления, прогресс и технические ошибки задания. Мы не запрашиваем пароль Кинопоиска.</li><li><b>Сессии:</b> access JWT в localStorage и httpOnly refresh-cookie; в базе хранится только хеш refresh-токена.</li></ul><p className="mt-2 text-muted-foreground">Пароли не хранятся в открытом виде. Аналитические трекеры, рекламные пиксели и продажа данных не используются.</p></section>
        <section><h2 className="font-bold text-base mb-2">3. Зачем это нужно</h2><p>Данные профиля нужны для синхронизации между устройствами, отображения истории и библиотеки, работы свайпов и персональных рекомендаций. Данные импорта нужны для сопоставления фильмов с TMDB и применения оценок в профиль.</p></section>
        <section><h2 className="font-bold text-base mb-2">4. Внешние сервисы</h2><p>Метаданные и изображения запрашиваются у TMDB; трейлеры могут встраиваться через YouTube; ссылка импорта обрабатывается сервисом импорта Кинопоиска. Эти поставщики применяют собственные политики конфиденциальности. Подробнее о контенте — на странице <Link href="/copyright" className="text-rating hover:underline">Правообладателям / Copyright</Link>.</p></section>
        <section><h2 className="font-bold text-base mb-2">5. Сроки хранения</h2><ul className="list-disc pl-5 space-y-1.5"><li>Данные активного аккаунта — пока аккаунт не удалён.</li><li>Refresh-сессии — до 30 дней, отозванные сессии удаляются при регламентной очистке.</li><li>Завершённые и отменённые задания импорта и их технические записи — не более 90 дней.</li><li>После удаления аккаунта профильные данные удаляются транзакционно сразу; резервные копии перезаписываются по циклу резервного копирования, но не позднее 30 дней.</li></ul></section>
        <section><h2 className="font-bold text-base mb-2 flex items-center gap-2"><Cookie className="h-4 w-4 text-rating" />6. Cookies и localStorage</h2><p>Refresh-cookie необходима для продления сессии и не используется для слежения. Access-токен хранится локально для авторизации API. Гостевые оценки и избранное могут оставаться только в браузере до его очистки.</p></section>
        <section><h2 className="font-bold text-base mb-2 flex items-center gap-2"><UserCheck className="h-4 w-4 text-rating" />7. Права пользователя</h2><p>Можно запросить доступ и выгрузку данных, исправление, отзыв согласия и удаление. Удаление доступно в профиле кнопкой «Удалить аккаунт и данные» и вызывает <code className="text-rating">DELETE /api/v1/account</code>. Для вопросов: <a href="mailto:steammail_38@mail.ru" className="text-rating hover:underline">steammail_38@mail.ru</a>.</p></section>
        <section><h2 className="font-bold text-base mb-2">8. Изменения и контакты</h2><p>При существенном изменении политики мы обновим версию и дату на этой странице. По privacy- и copyright-запросам пишите на <a href="mailto:steammail_38@mail.ru" className="text-rating hover:underline">steammail_38@mail.ru</a>; технические вопросы можно дополнительно задать в <a href="https://github.com/Vlan3ik/SwapKino/issues" target="_blank" rel="noopener noreferrer" className="text-rating hover:underline">GitHub Issues</a>.</p></section>
      </div>
    </motion.article>
  </div>;
}
