using System.Net.Http.Headers;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;

namespace SwapKino.Api;
public sealed class TmdbClient(IHttpClientFactory factory, IConfiguration config, SwapKinoDbContext db)
{
    public async Task<JsonDocument> Get(string path, Dictionary<string,string?> query, CancellationToken ct) { using var request = new HttpRequestMessage(HttpMethod.Get, path + "?" + string.Join("&", query.Where(x => x.Value is not null).Select(x => $"{x.Key}={Uri.EscapeDataString(x.Value!)}"))); var token = config["TMDB_ACCESS_TOKEN"]; if (!string.IsNullOrWhiteSpace(token)) request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token); else request.RequestUri = new Uri(request.RequestUri + $"&api_key={config["TMDB_API_KEY"]}", UriKind.Relative); var response = await factory.CreateClient("tmdb").SendAsync(request, ct); response.EnsureSuccessStatusCode(); return JsonDocument.Parse(await response.Content.ReadAsStringAsync(ct)); }
    public async Task<List<Movie>> Discover(int page, string? search, CancellationToken ct) { var json = await Get(search is null ? "/discover/movie" : "/search/movie", new() { ["language"]="ru-RU", ["page"]=page.ToString(), ["query"]=search, ["include_adult"]="false", ["sort_by"]="popularity.desc" }, ct); var result = new List<Movie>(); foreach (var x in json.RootElement.GetProperty("results").EnumerateArray()) { var id=x.GetProperty("id").GetInt32(); var movie=await db.Movies.FindAsync([id],ct) ?? new Movie { TmdbId=id }; movie.Title=x.TryGetProperty("title",out var title)?title.GetString()??"":movie.Title; movie.OriginalTitle=x.TryGetProperty("original_title",out var original)?original.GetString():movie.OriginalTitle; movie.Overview=x.TryGetProperty("overview",out var overview)?overview.GetString():movie.Overview; movie.ReleaseDate=x.TryGetProperty("release_date",out var date)?date.GetString():movie.ReleaseDate; movie.VoteAverage=x.TryGetProperty("vote_average",out var rating)?rating.GetDouble():movie.VoteAverage; movie.VoteCount=x.TryGetProperty("vote_count",out var votes)?votes.GetInt32():movie.VoteCount; movie.Popularity=x.TryGetProperty("popularity",out var pop)?pop.GetDouble():movie.Popularity; movie.PosterPath=x.TryGetProperty("poster_path",out var poster)?poster.GetString():movie.PosterPath; movie.BackdropPath=x.TryGetProperty("backdrop_path",out var back)?back.GetString():movie.BackdropPath; if (db.Entry(movie).State==EntityState.Detached) db.Movies.Add(movie); result.Add(movie); } await db.SaveChangesAsync(ct); return result; }
    public async Task<Movie> Details(int id, CancellationToken ct) { var json=await Get($"/movie/{id}",new(){["language"]="ru-RU",["append_to_response"]="credits,videos,watch/providers,keywords"},ct); var x=json.RootElement; var movie=await db.Movies.FindAsync([id],ct) ?? new Movie{TmdbId=id}; movie.Title=x.GetProperty("title").GetString()??movie.Title; movie.OriginalTitle=x.TryGetProperty("original_title",out var original)?original.GetString():null; movie.Overview=x.TryGetProperty("overview",out var overview)?overview.GetString():null; movie.ReleaseDate=x.TryGetProperty("release_date",out var date)?date.GetString():null; movie.RuntimeMinutes=x.TryGetProperty("runtime",out var runtime)&&runtime.ValueKind!=JsonValueKind.Null?runtime.GetInt32():null; movie.VoteAverage=x.GetProperty("vote_average").GetDouble(); movie.VoteCount=x.GetProperty("vote_count").GetInt32(); movie.Popularity=x.GetProperty("popularity").GetDouble(); movie.PosterPath=x.TryGetProperty("poster_path",out var poster)?poster.GetString():null; movie.BackdropPath=x.TryGetProperty("backdrop_path",out var back)?back.GetString():null; movie.DetailsState="ready"; movie.Payload=x.GetRawText(); if(db.Entry(movie).State==EntityState.Detached)db.Movies.Add(movie); await db.SaveChangesAsync(ct); return movie; }
}
